
development:
  adapter: postgresql
  database: personal
  username: owen
  password: 8445
  template: template0
  encoding: utf8
  pool: 5

production:
  adapter: postgresql
  database: personal
  username: owen
  password: 8445
  template: template0
  encoding: utf8
  pool: 5
